// 卫星相关常量映射 (数据来源: CelesTrak 及项目积累)

// 国家代码到中文名称的映射 (CelesTrak 格式)
export const COUNTRY_NAMES: Record<string, string> = {
  // 标准 ISO 2字母代码
  US: "美国",
  GB: "英国", // UK 也常用
  FR: "法国",
  CA: "加拿大",
  IT: "意大利",
  NZ: "新西兰",
  MA: "摩洛哥",
  IM: "马恩岛",
  AC: "阿森松岛",
  AB: "安提瓜和巴布达",
  AU: "澳大利亚",
  AT: "奥地利",
  BE: "比利时",
  CH: "瑞士",
  CZ: "捷克",
  DE: "德国", // GER 也常用
  DK: "丹麦",
  EE: "爱沙尼亚",
  ES: "西班牙",
  FI: "芬兰",
  GR: "希腊",
  HK: "香港",
  HU: "匈牙利",
  IE: "爱尔兰",
  IN: "印度",
  JP: "日本",
  KR: "韩国",
  LT: "立陶宛",
  LU: "卢森堡",
  LV: "拉脱维亚",
  NL: "荷兰",
  NO: "挪威",
  PL: "波兰",
  PT: "葡萄牙",
  RU: "俄罗斯",
  SE: "瑞典",
  SI: "斯洛文尼亚",
  SK: "斯洛伐克",
  TR: "土耳其",
  UA: "乌克兰",
  // CelesTrak 特殊格式
  CIS: "俄罗斯",
  PRC: "中国",
  CN: "中国",
  TWN: "中国台湾",
  JPN: "日本",
  IND: "印度",
  BRAZ: "巴西",
  ARGN: "阿根廷",
  MEX: "墨西哥",
  SAUD: "沙特阿拉伯",
  INDO: "印度尼西亚",
  TURK: "土耳其",
  NETH: "荷兰",
  THAI: "泰国",
  SAFR: "南非",
  UKR: "乌克兰",
  SING: "新加坡",
  POL: "波兰",
  SWED: "瑞典",
  NOR: "挪威",
  BEL: "比利时",
  MALA: "马来西亚",
  PAKI: "巴基斯坦",
  RP: "菲律宾",
  VENZ: "委内瑞拉",
  SWTZ: "瑞士",
  DEN: "丹麦",
  EGYP: "埃及",
  FIN: "芬兰",
  GREC: "希腊",
  IRAN: "伊朗",
  IRAQ: "伊拉克",
  KAZ: "哈萨克斯坦",
  KWT: "科威特",
  NIG: "尼日利亚",
  POR: "葡萄牙",
  SKOR: "韩国",
  UAE: "阿联酋",
  ISRA: "以色列",
  SPN: "西班牙",
  GER: "德国",
  CZE: "捷克",
  EST: "爱沙尼亚",
  HUN: "匈牙利",
  LTU: "立陶宛",
  BGR: "保加利亚",
  ROM: "罗马尼亚",
  SVN: "斯洛文尼亚",
  SVK: "斯洛伐克",
  HRV: "克罗地亚",
  AZER: "阿塞拜疆",
  MDA: "摩尔多瓦",
  MNG: "蒙古",
  NKOR: "朝鲜",
  LAOS: "老挝",
  BGD: "孟加拉国",
  LKA: "斯里兰卡",
  MMR: "缅甸",
  NPL: "尼泊尔",
  PER: "秘鲁",
  COL: "哥伦比亚",
  CHLE: "智利",
  BOL: "玻利维亚",
  PRY: "巴拉圭",
  URY: "乌拉圭",
  ECU: "厄瓜多尔",
  CRI: "哥斯达黎加",
  DJI: "吉布提",
  RWA: "卢旺达",
  UGA: "乌干达",
  GHA: "加纳",
  ZWE: "津巴布韦",
  BWA: "博茨瓦纳",
  MUS: "毛里求斯",
  AGO: "安哥拉",
  SDN: "苏丹",
  TUN: "突尼斯",
  ALG: "阿尔及利亚",
  QAT: "卡塔尔",
  BHR: "巴林",
  JOR: "约旦",
  PRI: "波多黎各",
  SLB: "所罗门群岛",
  MCO: "摩纳哥",
  KEN: "肯尼亚",
  VTNM: "越南",
  CHBZ: "瑞士",
  BELA: "白俄罗斯",
  ASRA: "奥地利",
  FGER: "法国/德国",
  FRIT: "法国/意大利",
  CZCH: "捷克",
  USBZ: "美国/巴西",
  // 历史国家
  SU: "苏联",
  // 国际组织
  ESA: "欧洲航天局",
  ESRO: "欧洲空间研究组织",
  EUTE: "欧洲通信卫星组织",
  EUME: "欧洲气象卫星组织",
  NATO: "北约",
  ITSO: "国际通信卫星组织",
  SES: "SES公司",
  O3B: "O3b网络",
  ORB: "轨道科学公司",
  GLOB: "全球星",
  STCT: "空间通信",
  RASC: "俄罗斯航天局",
  SEAL: "海射公司",
  ABS: "ABS公司",
  // CelesTrak I-* 格式 (国际组织)
  "I-INT": "国际通信卫星组织",
  "I-ESA": "欧洲航天局",
  "I-EU": "欧盟",
  "I-EUT": "欧洲通信卫星组织",
  "I-EUM": "欧洲气象卫星组织",
  "I-ARAB": "阿拉伯卫星通信组织",
  "I-INM": "国际移动卫星组织",
  "I-NATO": "北约",
  "I-RASC": "俄罗斯航天局",
  // 全名（部分数据使用全名而非代码）
  France: "法国",
  Russia: "俄罗斯",
  "New Zealand": "新西兰",
  Spain: "西班牙",
};

// 发射场映射 (数据来源: CelesTrak SATCAT Launch Sites)
// https://celestrak.org/satcat/launchsites.php
export const LAUNCH_SITES: Record<string, string> = {
  AFETR: "美国-佛罗里达州-空军东部试验场",
  AFWTR: "美国-加利福尼亚州-空军西部试验场",
  ANDSP: "挪威-诺尔兰郡-安岛航天港",
  ALCLC: "巴西-马拉尼昂州-阿拉卡蒂发射中心",
  BOS: "澳大利亚-昆士兰州-博文轨道航天港",
  CAS: "加那利群岛-空域",
  DLS: "俄罗斯-顿巴罗夫斯基-发射场",
  ERAS: "东部-空域",
  FRGUI: "法国-法属圭亚那-欧洲航天中心",
  HGSTR: "阿尔及利亚-哈马吉拉-空间跟踪场",
  JJSLA: "韩国-济州岛-海域发射区",
  JSC: "中国-甘肃-酒泉卫星发射中心",
  KODAK: "美国-阿拉斯加州-科迪亚克发射综合体",
  KSCUT: "日本-鹿儿岛县-内之浦宇宙空间观测所",
  KWAJ: "美国-夸贾林环礁-陆军基地",
  KYMSC: "俄罗斯-阿斯特拉罕州-卡普斯京亚尔导弹航天综合设施",
  NSC: "韩国-全罗南道-罗老航天中心",
  PLMSC: "俄罗斯-阿尔汉格尔斯克州-普列谢茨克航天发射场",
  RLLB: "新西兰-马希亚半岛-火箭实验室发射基地",
  SCSLA: "中国-南海-发射区",
  SEAL: "海上-移动发射平台",
  SEMLS: "伊朗-塞姆南卫星发射场",
  SMTS: "伊朗-沙赫鲁德导弹试验场",
  SNMLP: "肯尼亚-印度洋-圣马科发射平台",
  SPKII: "日本-和歌山县-纪伊半岛航天港",
  SRILR: "印度-安得拉邦-萨蒂什·达万航天中心",
  SUBL: "海上-潜艇移动发射平台",
  SVOBO: "俄罗斯-阿穆尔州-斯沃博德内发射场",
  TAISC: "中国-山西-太原卫星发射中心",
  TANSC: "日本-鹿儿岛县-种子岛航天中心",
  TYMSC: "哈萨克斯坦-拜科努尔-航天发射场",
  UNK: "未知",
  VOSTO: "俄罗斯-阿穆尔州-东方航天发射场",
  WLPIS: "美国-弗吉尼亚州-瓦罗普斯岛",
  WOMRA: "澳大利亚-南澳大利亚州-乌梅拉",
  WRAS: "西部-空域",
  WSC: "中国-海南-文昌航天发射场",
  XICLF: "中国-四川-西昌卫星发射中心",
  YAVNE: "以色列-南部亚夫内发射场",
  YSLA: "中国-黄海发射区",
  YUN: "朝鲜-平安北道-云城发射场（西海卫星发射场）",
};

// 对象类型映射
export const OBJECT_TYPES: Record<string, { label: string; class: string }> = {
  PAYLOAD: { label: "有效载荷", class: "payload" },
  "ROCKET BODY": { label: "火箭体", class: "rocket" },
  DEBRIS: { label: "碎片", class: "debris" },
};

// 状态映射
export const STATUS_LABELS: Record<string, string> = {
  "+": "在轨运行",
  "-": "未运行",
  D: "已衰减",
  P: "部分衰减",
  B: "备份",
  S: "储备",
  X: "试验",
  "N/A": "不适用",
};

// 任务分类映射（与后端一致）
export const MISSION_CATEGORIES: Record<string, string> = {
  // 通信类
  "Civil Communications": "通信",
  "Defense Communications": "通信",
  "Commercial Communications": "通信",
  Communications: "通信",
  Telecommunications: "通信",
  Broadcasting: "通信",
  "Mobile Communications": "通信",
  "Fixed Satellite Services": "通信",

  // 导航类
  "Civil Navigation": "导航",
  "Defense Navigation": "导航",
  "Commercial Navigation": "导航",
  Navigation: "导航",
  Positioning: "导航",
  GNSS: "导航",
  GPS: "导航",
  GLONASS: "导航",
  Galileo: "导航",
  BeiDou: "导航",

  // 遥感/对地观测类
  "Civil Imaging": "遥感",
  "Civil Earth Observation": "遥感",
  "Civil Remote Sensing": "遥感",
  "Defense Imaging": "遥感",
  "Defense Earth Observation": "遥感",
  "Defense Reconnaissance": "遥感",
  "Commercial Imaging": "遥感",
  "Commercial Remote Sensing": "遥感",
  "Earth Observation": "遥感",
  "Remote Sensing": "遥感",
  Imaging: "遥感",
  Reconnaissance: "遥感",
  Surveillance: "遥感",
  Mapping: "遥感",
  Cartography: "遥感",
  "Terrain Mapping": "遥感",
  Oceanography: "遥感",
  "Marine Observation": "遥感",
  "Land Observation": "遥感",

  // 气象类
  "Civil Weather": "气象",
  "Defense Weather": "气象",
  "Commercial Weather": "气象",
  Weather: "气象",
  Meteorological: "气象",
  Meteorology: "气象",
  Climate: "气象",
  "Climate Research": "气象",
  "Environmental Monitoring": "气象",

  // 科学研究类
  "Civil Science": "科学",
  "Civil Technology": "科学",
  "Defense Science": "科学",
  "Scientific Research": "科学",
  "Space Science": "科学",
  "Earth Science": "科学",
  Astronomy: "科学",
  Astrophysics: "科学",
  Geodetic: "科学",
  Geodesy: "科学",
  Geophysical: "科学",
  Geophysics: "科学",
  Biological: "科学",
  Biology: "科学",
  Materials: "科学",
  "Materials Science": "科学",
  Physics: "科学",
  "Solar Physics": "科学",
  "Space Physics": "科学",
  "Plasma Physics": "科学",
  "Cosmic Ray": "科学",
  "Particle Physics": "科学",

  // 技术试验类
  "Technology Demonstration": "技术试验",
  "Civil Experimental": "技术试验",
  "Defense Technology": "技术试验",
  Experimental: "技术试验",
  Test: "技术试验",
  "Technology Development": "技术试验",
  Technology: "技术试验",
  Demonstration: "技术试验",
  Prototype: "技术试验",
  Engineering: "技术试验",

  // 国防军事类
  "Defense Sigint": "国防",
  "Defense Early Warning": "国防",
  Defense: "国防",
  Military: "国防",
  "Missile Warning": "国防",
  "Nuclear Detection": "国防",
  "Electronic Intelligence": "国防",
  "Signals Intelligence": "国防",
  ELINT: "国防",
  SIGINT: "国防",

  // 载人航天类
  "Space Station": "载人航天",
  Manned: "载人航天",
  Crewed: "载人航天",
  Cargo: "载人航天",
  Supply: "载人航天",
  "Human Spaceflight": "载人航天",
  "Space Tourism": "载人航天",

  // 数据中继类
  "Data Relay": "数据中继",
  "Tracking and Data Relay": "数据中继",
  TDRS: "数据中继",
  "Satellite Inter-satellite Link": "数据中继",

  // 其他
  "Civil Education": "教育",
  Education: "教育",
  Academic: "教育",
  Amateur: "业余无线电",
  "Amateur Radio": "业余无线电",
  Rescue: "搜救",
  "Search and Rescue": "搜救",
  SAR: "搜救",
  Training: "训练",
  " Calibration": "校准",
  Tracking: "跟踪",
  "Space Debris": "碎片",
  Debris: "碎片",
};

// 类型守卫函数
export function isObjectType(type: string): type is keyof typeof OBJECT_TYPES {
  return type in OBJECT_TYPES;
}
